version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
        - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongo:/data/db

  scrapy:
    build : ./steam
    container_name: steam
  
  flask:
    build: .
    container_name: flask
    ports: 
      - 8050:8050
    environment:
      FLASK_ENV: development
    command: ["python","app.py"]
